### ISSUE TITLE
Static files not working when deployed

### ISSUE THREAD

**Issue by wezm** [satyarohith/sift#29]
Static files are not served on Deno Deploy; images are corrupt locally and when deployed.

I've created a sample project to reproduce this issue: https://github.com/wezm/repro-sift-static

In Deno Deploy it's linked to <https://github.com/wezm/repro-sift-static/blob/main/src/index.ts>, accessible at <https://quiet-owl-61.deno.dev/>.

<img width="945" alt="Screenshot 2021-07-09 at 08-50-55 Deno" src="https://user-images.githubusercontent.com/21787/125000062-e1054c80-e092-11eb-9920-61c1126aec89.png">

When running locally with `deployctl run --watch --libs=ns,fetchevent --addr :8888 src/index.ts` the style sheet loads properly (somtimes) but when deployed it does not. The image does not load locally or when deployed.

**Comment by nhrones** [comment]
When I run   https://quiet-owl-61.deno.dev/
Open the chrome-develop-tools select the network tab, then refresh the page, 
I see that the image.png is loading as 'type json'
If you click on the file in the list you can examine the headers.
image,png should have a content type of ' image/png ', not 'application/json'
Also, there is an error message for response that says {"error":"Headers are immutable."}
This had to happen in sift. 
Perhaps Sift is trying to mutate the contentType header instead of replacing it.

**Comment by nhrones** [comment]
@satyarohith  looks like sift may be trying to mutate the contentType header. see above.

**Comment by nhrones** [comment]
@satyarohith 
The browser will reject a mutated headers object

```js
// in line 76 you are trying to mutate the existing header
for (const [key, value] of newHeaders) {
   existingHeaders.set(key, value);
}
```
Instead, build a fresh set of headers from the existing
and the browser will accept them.

```js
// replace with the following 
// first place the existingHeaders in a new headers object
const newHeaders = new Headers(existingHeaders);
// do any housekeeping with this set...
 if (newHeaders.has("x-github-request-id")) {
    newHeaders.delete("content-security-policy");
  }
// then add you contentType header...
  for (const [key, value] of headers) {
    newHeaders.set(key, value);
  }
// finally, return the newHeaders object in a new Responce object
// line 80
  return new Response(res.body, {
    headers: newHeaders,
    status: res.status,
    statusText: res.statusText,
  });
```

**Comment by satyarohith** [comment]
Thanks for looking into it, @nhrones! That's the root cause. Are you interested in opening a PR?

**Comment by nhrones** [comment]
I'm a total noob on GitHub. I've tried to help in DenoCtl but so far no
luck.  I'm an old retired C# developer and i've fallen in love with
Typescript/Deno.
I can try again with a little hand holding.
a. clone repo
b. make changes
c. pull request
??

**Comment by nhrones** [comment]
I'm sorry, but the crap that is showing up in my Gmail web client is
impossible to work with.
It's so sad to see such crappy technology in this day and age.

**Comment by satyarohith** [comment]
> a. clone repo
b. make changes
c. pull request

These are the only steps to get started. It's similar to how you opened https://github.com/denoland/deployctl/pull/67. :)

**Comment by nhrones** [comment]
How do I stop getting these emails on Gmail?  Whatever Git is sending is
Way too hard to use on Gmail-WebPage.

**Comment by nhrones** [comment]
@satyarohith  please forgive my rants.  I fixed my Gmail (had a bad theme that mangled everything from Github)..
Are you still interest in help?

**Comment by satyarohith** [comment]
Thanks for the patience, @wezm! I fixed the issue and released a new version [`0.3.4`](https://github.com/satyarohith/sift/releases/tag/0.3.4). Please try it out and let me know if you face any issues.

>  The image does not load locally or when deployed.

There's a tracking issue (https://github.com/denoland/deployctl/issues/60) on deployctl. But you'll soon be able to run `sift` using `deno` without the need for `deployctl`, which should fix the local static assets issue.

**Comment by wezm** [comment]
Wonderful, confirming that that image and stylesheet now work.

**Comment by sylc** [comment]
Hi, i'm having a similar issue. I'm using sift 0.3.4 and deployctl 0.3.0. (also tried with main)

my code: https://github.com/sylc/test_sift/blob/main/server.ts.
deployment: https://old-donkey-81.deno.dev/

![image](https://user-images.githubusercontent.com/10268458/126336394-cf7fe609-abfa-4375-aac3-adf55d84c950.png)


- with deploctl, the style file is loaded but the png file is not showing (the response is noted as 200 in devTools)
- when deployed, neither the styling or the png is loaded (there is no response) 


I also cloned wezm code to test with my local deployctl. The image is not loading correctly. 

I have deno version  1.12.1

**Comment by wezm** [comment]
@sylc. See note above with the link to https://github.com/denoland/deployctl/issues/60. Images won't load properly locally but as of 0.3.4 they are now loading when deployed (for me).

**Comment by satyarohith** [comment]
@sylc, the website seems to be working fine for me on Chrome and Safari.
<img width="350" alt="CleanShot 2021-07-21 at 10 26 43@2x" src="https://user-images.githubusercontent.com/29819102/126433173-f6d02dae-b323-4ea2-90ce-33ae121e3992.png">

**Comment by sylc** [comment]
@wezm @satyarohith Thanks for the feedback.

It seems that i was facing 2 issue: 
- the local issue is due to the deployctl bug.
- the deno deployment issue is a csp issue. I'm normally using chrome. in devtools console there is `Refused to load the stylesheet 'https://old-donkey-81.deno.dev/assets/styles.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.` 
 
I tried in edge and firefox and the image was loaded successfully at first. But then I open the devtools and disable the cache and reload and I get the same error in both browser.  I guess i can try to set a meta tag in the head but i would expect the server to handle this by a header in the response. It is unclear why this is not happening on  @wezm repro site.

**Comment by nhrones** [comment]
@sylc @satyarohith  I get the same errors as you. On  https://old-donkey-81.deno.dev/.
Both the stylesheet and the img are rejected. Windows 10/ Chrome browser.  I had set up a test app after 0.3.4 and for several
hours testing the error I was getting just went away?  I looked on Discord but could see no reason for that to have happened.
The error I was testing for was a header mutation error in chrome.  I first saw it on @wezm app from  to denoland/deployctl#60.  My test was producing the mutated header rejection, and after a few hours, it changed to a content-type error???

**Comment by sylc** [comment]
In my test case I'm retrieving the `index.html` from github. 
If I instead replace it with a baked in response in serve eg: `'/':  () => new Response(html, { headers: { "content-type": "text/html; charset=UTF-8", } }),` (similar to @wezm initial site),  then it is working.
I can see that any files retrieved from github has a `content-security-policy` header set, which does not allow to load further files
It seems that that there is an attempt in the code to remove this header. ref https://github.com/satyarohith/sift/blob/2088f39cd35e7ade542abb5fde3ecc308d11839c/mod.ts#L74     This does not seem to work as intended

**Comment by nhrones** [comment]
@satyarohith @sylc 
Please note that in line#74, the case may be that you are not actually removing the header. Often, as was the case with content-type header, mutation is blocked on original header but not on NEW header.
Consider  ...
```js
// here originalResponse.headers will be the init values of a new headers object
const newHeaders = new Headers(originalResponse.headers)
// now you may be able to make changes.  Worth a try.
newHeaders.delete("content-security-policy"); 
```
As with the content-type issue, the newHeaders object should allow mutations.

**Comment by nhrones** [comment]
You might just log out the original headers after the delete attempt, just to verify the deletion.

**Comment by nhrones** [comment]
@sylc @satyarohith
I'm wrong again.  Did some testing.  I forgot that the new Response object on line#65 also returns a new Headers object.  So yes the header delete will happen.  What confused me was the reuse of the param 'response' to new.  I saw the name at params and thought it was what was referenced at line#74  response.headers.delete.
Sorry!
