### ISSUE TITLE
404 error on importing sift

### ISSUE THREAD

**Issue by arnu515** [satyarohith/sift#52]
Importing the latest version of `sift` and running `deno cache` gives this error:

```shell
$ deno cache index.ts
Download https://raw.githubusercontent.com/usesift/media_types/34656bf398c81f2687fa5010e56844dac4e7a2e9/mod.ts
error: Import 'https://raw.githubusercontent.com/usesift/media_types/34656bf398c81f2687fa5010e56844dac4e7a2e9/mod.ts' failed: 404 Not Found
```

The fix would be to bump `media_types` from `2.10` to `2.11.1`.

I've created a pull request for you, so you can just merge it.

Thanks

**Comment by arnu515** [comment]
@satyarohith can you create a new release?

Thanks.

**Comment by satyarohith** [comment]
@arnu515, this version uses the official version of media_types and it works.
```ts
import { serve } from "https://deno.land/x/sift@0.4.2/mod.ts";

serve({
  "/": () => new Response("hello world"),
  "/blog/:slug": (request, params) => {
    const post = `Hello, you visited ${params.slug}!`;
    return new Response(post);
  },
  // The route handler of 404 will be invoked when a route handler
  // for the requested path is not found.
  404: () => new Response("not found"),
});
```

**Comment by arnu515** [comment]
@satyarohith it works now. It didn't work earlier for me, and I had to manually bump the version of media_types by cloning the source code of sift.

[Here's the bugged Repl](https://replit.com/@Arnu515/SimpleAuthBackend#index.ts), if you could have a look.

Thanks.
