### ISSUE TITLE
0.3.4 broken

### ISSUE THREAD

**Issue by wezm** [satyarohith/sift#66]
I was using version 0.3.4 in a small application via: <https://deno.land/x/sift@0.3.4/mod.ts>. This [imports the following](https://deno.land/x/sift@0.3.4/mod.ts#L12):

```
import {  contentType as getContentType,  lookup,} from "https://raw.githubusercontent.com/usesift/media_types/34656bf398c81f2687fa5010e56844dac4e7a2e9/mod.ts";
```

but that returns 404. The solution is probably to update to a newer version of sift but I wanted to note this because ideally previously published versions would continue working.

**Comment by satyarohith** [comment]
Hi @wezm, thanks for opening the issue. Deno introduced `deno vendor` command to handle these problems.

You can use `deno vendor` on your final application. It will cache all the dependencies into a folder that you can commit to git.

Note: `deno vendor` uses import maps. You can deploy the application only using "GitHub Actions"  (https://deno.com/deploy/docs/projects#git-integration) mode at the moment as import maps are not supported on "Automatic" mode.

**Comment by wezm** [comment]
Ok thanks @satyarohith I'll give that a go.
