### ISSUE TITLE
Unresolvable dependency import, in 0.5.0

### ISSUE THREAD

**Issue by milotheirself** [satyarohith/sift#70]
[`x.lcas.dev/preact`](https://x.lcas.dev/preact) imports in `mod.ts` are currently not resolvable.

```plain
error: Uncaught (in promise) TypeError: error sending request for url (https://x.lcas.dev/preact@10.5.12/mod.js): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)
    at https://deno.land/x/sift@0.5.0/mod.ts:24:15
  await import(entrypoint);
```

Can someone reproduce this?

**Comment by nailuj29** [comment]
I can reproduce this

**Comment by jerrygreen** [comment]
Same here

**Comment by satyarohith** [comment]
Is anyone interested in taking this up?

We should replace https://x.lcas.dev/preact with https://esm.sh/preact and https://esm.sh/preact-render-to-string for SSR.

**Comment by nailuj29** [comment]
I'll be able to make a PR in a few hours.

**Comment by milotheirself** [comment]
@satyarohith, can #71 or #72 be merged?
