### ISSUE TITLE
add examples

### ISSUE THREAD

**Issue by satyarohith** [satyarohith/sift#8]
There are a lot of Deno Deploy apps already using sift. We need to add links to them in the readme.

**Comment by elycheikhsmail** [comment]
> There are a lot of Deno Deploy apps already using sift. We need to add links to them in the readme.

I think so, in fact examples and doc make easy to rewrite some rest api app to use deno deploy instead of python or node or other lang

**Comment by satyarohith** [comment]
I had to write some examples for tests https://github.com/satyarohith/sift/tree/main/examples.

I'm closing this issue considering that we now have the ground to build on top off.
